#!/bin/bash                                                                                                                           
                                                                                                                                      
echo "export http_proxy=http://localhost:8123"                                                                                        
                                                                                                                                      
CACHE_DIR="$PWD/cache"

mkdir -p "$CACHE_DIR"
polipo diskCacheRoot="$CACHE_DIR" diskCacheTruncateSize=1000000000

