#!/bin/bash

apt-get update
apt-get -y install netbase nano screen less

cat << EOF >> /etc/modules
vchiq
snd_bcm2835
EOF

sed -i -e 's/KERNEL\!=\"eth\*|/KERNEL\!=\"/' /lib/udev/rules.d/75-persistent-net-generator.rules
rm -f /etc/udev/rules.d/70-persistent-net.rules

update-rc.d networking defaults
